# 1. Import Libraries

In [1]:
# Import libraries

import pandas as pd
import numpy as np
import os

# 2. Importing Data

In [2]:
# Turn project folder path into a string
path = r'/Users/thomasradio/Documents/Jupyter/230808 Tom Radio Achievement 6 Project'

In [3]:
# Check path
path

'/Users/thomasradio/Documents/Jupyter/230808 Tom Radio Achievement 6 Project'

In [4]:
# Import pugetsound_currents_clean.pkl dataset
pugetsound_currents_clean = pd.read_pickle(os.path.join(path, '02 Data', 'Prepared Data', 'pugetsound_currents_clean.pkl'))

In [5]:
pugetsound_currents_clean.head()

,Dive_Site,Date,Day_of_Week,Time,Event,Current_Speed_(knots),Current_Station_Name,Current_Station_ID,Latitude,Longitude
0,Deception Pass,2024-01-01,Monday,00:48,slack,0.0,DECEPTION PASS NARROWS,PUG1701,48.405722,-122.6449
1,Deception Pass,2024-01-01,Monday,03:18,flood,4.0,DECEPTION PASS NARROWS,PUG1701,48.405722,-122.6449
2,Deception Pass,2024-01-01,Monday,06:42,slack,0.0,DECEPTION PASS NARROWS,PUG1701,48.405722,-122.6449
3,Deception Pass,2024-01-01,Monday,09:30,ebb,-5.3,DECEPTION PASS NARROWS,PUG1701,48.405722,-122.6449
4,Deception Pass,2024-01-01,Monday,13:42,slack,0.0,DECEPTION PASS NARROWS,PUG1701,48.405722,-122.6449

In [6]:
# Import pugetsound_tides_clean.pkl dataset
pugetsound_tides_clean = pd.read_pickle(os.path.join(path, '02 Data', 'Prepared Data', 'pugetsound_tides_clean.pkl'))

In [7]:
pugetsound_tides_clean.head()

,Dive_Site,Date,Day_of_Week,Time,Event,Height (cm),Height (ft),Tide_Station_Name,Tide_Station_ID,Latitude,Longitude
0,Deception Pass,2024-01-01,Monday,02:01,Low,19,0.62,"CORNET BAY, DECEPTION PASS",9447995,48.405722,-122.6449
1,Deception Pass,2024-01-01,Monday,09:12,High,324,10.63,"CORNET BAY, DECEPTION PASS",9447995,48.405722,-122.6449
2,Deception Pass,2024-01-01,Monday,15:49,Low,172,5.65,"CORNET BAY, DECEPTION PASS",9447995,48.405722,-122.6449
3,Deception Pass,2024-01-01,Monday,20:13,High,218,7.16,"CORNET BAY, DECEPTION PASS",9447995,48.405722,-122.6449
4,Deception Pass,2024-01-02,Tuesday,02:39,Low,55,1.79,"CORNET BAY, DECEPTION PASS",9447995,48.405722,-122.6449

In [8]:
pugetsound_currents_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11000 entries, 0 to 10999
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Dive_Site              11000 non-null  object
 1   Date                   11000 non-null  datetime64[ns]
 2   Day_of_Week            11000 non-null  object
 3   Time                   11000 non-null  object
 4   Event                  11000 non-null  object
 5   Current_Speed_(knots)  11000 non-null  float64
 6   Current_Station_Name   11000 non-null  object
 7   Current_Station_ID     11000 non-null  object
 8   Latitude               11000 non-null  float64
 9   Longitude              11000 non-null  float64
dtypes: datetime64[ns](1), float64(3), object(6)
memory usage: 859.5+ KB

In [9]:
pugetsound_tides_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5626 entries, 0 to 5625
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Dive_Site          5626 non-null   object
 1   Date               5626 non-null   datetime64[ns]
 2   Day_of_Week        5626 non-null   object
 3   Time               5626 non-null   object
 4   Event              5626 non-null   object
 5   Height (cm)        5626 non-null   int64
 6   Height (ft)        5626 non-null   float64
 7   Tide_Station_Name  5626 non-null   object
 8   Tide_Station_ID    5626 non-null   object
 9   Latitude           5626 non-null   float64
 10  Longitude          5626 non-null   float64
dtypes: datetime64[ns](1), float64(3), int64(1), object(6)
memory usage: 483.6+ KB

In [23]:
# Import 2024 Lunar Data.csv dataset
lunar = pd.read_csv(os.path.join(path, '02 Data', 'Prepared Data', 'lunar_data_clean.csv'))

In [24]:
lunar.head()

     Date  Moon Illuminated
0  1/1/24              0.75
1  1/2/24              0.67
2  1/3/24              0.58
3  1/4/24              0.48
4  1/5/24              0.39

In [27]:
lunar.tail()

         Date  Moon Illuminated
361  12/27/24              0.13
362  12/28/24              0.07
363  12/29/24              0.03
364  12/30/24              0.01
365  12/31/24              0.00

In [26]:
lunar.shape

(366, 2)

In [29]:
lunar.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 366 entries, 0 to 365
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Date              366 non-null    object
 1   Moon Illuminated  366 non-null    float64
dtypes: float64(1), object(1)
memory usage: 5.8+ KB

# Merge Datasets

In [10]:
# Define the common columns to merge on
merge_columns = ['Dive_Site', 'Date', 'Day_of_Week', 'Time', 'Event', 'Latitude', 'Longitude']

In [11]:
# Merge pugetsound_currents_clean and pugetsound_tides_clean using a full outer join
merged_data = pugetsound_currents_clean.merge(pugetsound_tides_clean, on=merge_columns, how='outer')

In [12]:
# Convert the "Time" column to datetime time format
merged_data['Time'] = pd.to_datetime(merged_data['Time'], format='%H:%M').dt.time

In [13]:
merged_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 16626 entries, 0 to 16625
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Dive_Site              16626 non-null  object
 1   Date                   16626 non-null  datetime64[ns]
 2   Day_of_Week            16626 non-null  object
 3   Time                   16626 non-null  object
 4   Event                  16626 non-null  object
 5   Current_Speed_(knots)  11000 non-null  float64
 6   Current_Station_Name   11000 non-null  object
 7   Current_Station_ID     11000 non-null  object
 8   Latitude               16626 non-null  float64
 9   Longitude              16626 non-null  float64
 10  Height (cm)            5626 non-null   float64
 11  Height (ft)            5626 non-null   float64
 12  Tide_Station_Name      5626 non-null   object
 13  Tide_Station_ID        5626 non-null   object
dtypes: datetime64[ns](1), float64(5), object(8)
memory usage: 1.9+ MB

In [14]:
# Convert the "Time" column to string format
merged_data['Time'] = merged_data['Time'].astype(str)

# Convert the "Time" column to datetime format and extract the time component
merged_data['Time'] = pd.to_datetime(merged_data['Time'], format='%H:%M:%S').dt.time

# Display the updated data types
print(merged_data.dtypes)

Dive_Site                        object
Date                     datetime64[ns]
Day_of_Week                      object
Time                             object
Event                            object
Current_Speed_(knots)           float64
Current_Station_Name             object
Current_Station_ID               object
Latitude                        float64
Longitude                       float64
Height (cm)                     float64
Height (ft)                     float64
Tide_Station_Name                object
Tide_Station_ID                  object
dtype: object

In [15]:
# Sort the merged_data dataframe
sorted_data = merged_data.sort_values(by=['Dive_Site', 'Date', 'Time'])

In [16]:
# Rename the sorted_data dataset to pugetsound_tides_currents
pugetsound_tides_currents = sorted_data.copy()

In [17]:
pugetsound_tides_currents.head(50)

,Dive_Site,Date,Day_of_Week,Time,Event,Current_Speed_(knots),Current_Station_Name,Current_Station_ID,Latitude,Longitude,Height (cm),Height (ft),Tide_Station_Name,Tide_Station_ID
2829,Alki,2024-01-01,Monday,00:24:00,ebb,-0.5,HARBOR ISLAND WEST,PUG1507,47.588707,-122.380009,NaN,NaN,NaN,NaN
12415,Alki,2024-01-01,Monday,01:34:00,Low,NaN,NaN,NaN,47.588707,-122.380009,20.0,0.66,LOCKHEED SHIPYARD,9447110
2830,Alki,2024-01-01,Monday,04:00:00,slack,0.0,HARBOR ISLAND WEST,PUG1508,47.588707,-122.380009,NaN,NaN,NaN,NaN
2831,Alki,2024-01-01,Monday,06:12:00,flood,0.1,HARBOR ISLAND WEST,PUG1509,47.588707,-122.380009,NaN,NaN,NaN,NaN
2832,Alki,2024-01-01,Monday,08:36:00,slack,0.0,HARBOR ISLAND WEST,PUG1510,47.588707,-122.380009,NaN,NaN,NaN,NaN
12416,Alki,2024-01-01,Monday,08:56:00,High,NaN,NaN,NaN,47.588707,-122.380009,364.0,11.95,LOCKHEED SHIPYARD,9447110
2833,Alki,2024-01-01,Monday,12:12:00,ebb,-0.2,HARBOR ISLAND WEST,PUG1511,47.588707,-122.380009,NaN,NaN,NaN,NaN
2834,Alki,2024-01-01,Monday,14:24:00,slack,0.0,HARBOR ISLAND WEST,PUG1512,47.588707,-122.380009,NaN,NaN,NaN,NaN
12417,Alki,2024-01-01,Monday,15:22:00,Low,NaN,NaN,NaN,47.588707,-122.380009,181.0,5.95,LOCKHEED SHIPYARD,9447110
2835,Alki,2024-01-01,Monday,17:24:00,slack,0.0,HARBOR ISLAND WEST,PUG1513,47.588707,-122.380009,NaN,NaN,NaN,NaN
12418,Alki,2024-01-01,Monday,19:57:00,High,NaN,NaN,NaN,47.588707,-122.380009,245.0,8.05,LOCKHEED SHIPYARD,9447110
2836,Alki,2024-01-02,Tuesday,01:18:00,ebb,-0.4,HARBOR ISLAND WEST,PUG1514,47.588707,-122.380009,NaN,NaN,NaN,NaN
12419,Alki,2024-01-02,Tuesday,02:12:00,Low,NaN,NaN,NaN,47.588707,-122.380009,58.0,1.89,LOCKHEED SHIPYARD,9447110
2837,Alki,2024-01-02,Tuesday,04:42:00,slack,0.0,HARBOR ISLAND WEST,PUG1515,47.588707,-122.380009,NaN,NaN,NaN,NaN
2838,Alki,2024-01-02,Tuesday,07:06:00,flood,0.1,HARBOR ISLAND WEST,PUG1516,47.588707,-122.380009,NaN,NaN,NaN,NaN
2839,Alki,2024-01-02,Tuesday,09:24:00,slack,0.0,HARBOR ISLAND WEST,PUG1517,47.588707,-122.380009,NaN,NaN,NaN,NaN
12420,Alki,2024-01-02,Tuesday,09:27:00,High,NaN,NaN,NaN,47.588707,-122.380009,361.0,11.84,LOCKHEED SHIPYARD,9447110
2840,Alki,2024-01-02,Tuesday,13:12:00,ebb,-0.2,HARBOR ISLAND WEST,PUG1518,47.588707,-122.380009,NaN,NaN,NaN,NaN
12421,Alki,2024-01-02,Tuesday,16:11:00,Low,NaN,NaN,NaN,47.588707,-122.380009,155.0,5.09,LOCKHEED SHIPYARD,9447110
2841,Alki,2024-01-02,Tuesday,16:42:00,slack,0.0,HARBOR ISLAND WEST,PUG1519,47.588707,-122.380009,NaN,NaN,NaN,NaN
2842,Alki,2024-01-02,Tuesday,19:00:00,slack,0.0,HARBOR ISLAND WEST,PUG1520,47.588707,-122.380009,NaN,NaN,NaN,NaN
2843,Alki,2024-01-02,Tuesday,20:24:00,slack,0.0,HARBOR ISLAND WEST,PUG1521,47.588707,-122.380009,NaN,NaN,NaN,NaN
12422,Alki,2024-01-02,Tuesday,21:07:00,High,NaN,NaN,NaN,47.588707,-122.380009,230.0,7.54,LOCKHEED SHIPYARD,9447110
2844,Alki,2024-01-03,Wednesday,02:12:00,ebb,-0.3,HARBOR ISLAND WEST,PUG1522,47.588707,-122.380009,NaN,NaN,NaN,NaN
12423,Alki,2024-01-03,Wednesday,02:52:00,Low,NaN,NaN,NaN,47.588707,-122.380009,102.0,3.34,LOCKHEED SHIPYARD,9447110
2845,Alki,2024-01-03,Wednesday,05:12:00,slack,0.0,HARBOR ISLAND WEST,PUG1523,47.588707,-122.380009,NaN,NaN,NaN,NaN
2846,Alki,2024-01-03,Wednesday,08:12:00,flood,0.1,HARBOR ISLAND WEST,PUG1524,47.588707,-122.380009,NaN,NaN,NaN,NaN
12424,Alki,2024-01-03,Wednesday,09:59:00,High,NaN,NaN,NaN,47.588707,-122.380009,356.0,11.68,LOCKHEED SHIPYARD,9447110
2847,Alki,2024-01-03,Wednesday,10:12:00,slack,0.0,HARBOR ISLAND WEST,PUG1525,47.588707,-122.380009,NaN,NaN,NaN,NaN
2848,Alki,2024-01-03,Wednesday,14:30:00,ebb,-0.3,HARBOR ISLAND WEST,PUG1526,47.588707,-122.380009,NaN,NaN,NaN,NaN
12425,Alki,2024-01-03,Wednesday,17:00:00,Low,NaN,NaN,NaN,47.588707,-122.380009,125.0,4.09,LOCKHEED SHIPYARD,9447110
2849,Alki,2024-01-03,Wednesday,20:54:00,slack,0.0,HARBOR ISLAND WEST,PUG1527,47.588707,-122.380009,NaN,NaN,NaN,NaN
2850,Alki,2024-01-03,Wednesday,22:06:00,slack,0.0,HARBOR ISLAND WEST,PUG1528,47.588707,-122.380009,NaN,NaN,NaN,NaN
12426,Alki,2024-01-03,Wednesday,22:32:00,High,NaN,NaN,NaN,47.588707,-122.380009,223.0,7.33,LOCKHEED SHIPYARD,9447110
2851,Alki,2024-01-04,Thursday,03:00:00,ebb,-0.2,HARBOR ISLAND WEST,PUG1529,47.588707,-122.380009,NaN,NaN,NaN,NaN
12427,Alki,2024-01-04,Thursday,03:35:00,Low,NaN,NaN,NaN,47.588707,-122.380009,150.0,4.93,LOCKHEED SHIPYARD,9447110
2852,Alki,2024-01-04,Thursday,05:24:00,slack,0.0,HARBOR ISLAND WEST,PUG1530,47.588707,-122.380009,NaN,NaN,NaN,NaN
2853,Alki,2024-01-04,Thursday,08:54:00,flood,0.1,HARBOR ISLAND WEST,PUG1531,47.588707,-122.380009,NaN,NaN,NaN,NaN
12428,Alki,2024-01-04,Thursday,10:31:00,High,NaN,NaN,NaN,47.588707,-122.380009,350.0,11.48,LOCKHEED SHIPYARD,9447110
2854,Alki,2024-01-04,Thursday,10:48:00,slack,0.0,HARBOR ISLAND WEST,PUG1532,47.588707,-122.380009,NaN,NaN,NaN,NaN
2855,Alki,2024-01-04,Thursday,15:30:00,ebb,-0.4,HARBOR ISLAND WEST,PUG1533,47.588707,-122.380009,NaN,NaN,NaN,NaN
12429,Alki,2024-01-04,Thursday,17:46:00,Low,NaN,NaN,NaN,47.588707,-122.380009,91.0,2.99,LOCKHEED SHIPYARD,9447110
2856,Alki,2024-01-04,Thursday,20:48:00,slack,0.0,HARBOR ISLAND WEST,PUG1534,47.588707,-122.380009,NaN,NaN,NaN,NaN
12430,Alki,2024-01-05,Friday,00:15:00,High,NaN,NaN,NaN,47.588707,-122.380009,234.0,7.67,LOCKHEED SHIPYARD,9447110
2857,Alki,2024-01-05,Friday,00:24:00,slack,0.0,HARBOR ISLAND WEST,PUG1535,47.588707,-122.380009,NaN,NaN,NaN,NaN
2858,Alki,2024-01-05,Friday,03:54:00,ebb,-0.1,HARBOR ISLAND WEST,PUG1536,47.588707,-122.380009,NaN,NaN,NaN,NaN
12431,Alki,2024-01-05,Friday,04:30:00,Low,NaN,NaN,NaN,47.588707,-122.380009,198.0,6.51,LOCKHEED SHIPYARD,9447110
2859,Alki,2024-01-05,Friday,05:48:00,slack,0.0,HARBOR ISLAND WEST,PUG1537,47.588707,-122.380009,NaN,NaN,NaN,NaN
2860,Alki,2024-01-05,Friday,09:24:00,flood,0.1,HARBOR ISLAND WEST,PUG1538,47.588707,-122.380009,NaN,NaN,NaN,NaN
12432,Alki,2024-01-05,Friday,11:05:00,High,NaN,NaN,NaN,47.588707,-122.380009,343.0,11.25,LOCKHEED SHIPYARD,9447110

In [18]:
# Reorder the columns in the desired order
column_order = ['Dive_Site', 'Date', 'Day_of_Week', 'Time', 'Event', 'Current_Speed_(knots)', 'Height (cm)', 'Height (ft)', 'Current_Station_Name', 'Current_Station_ID', 'Tide_Station_Name', 'Tide_Station_ID', 'Latitude', 'Longitude']
pugetsound_tides_currents = pugetsound_tides_currents[column_order]

In [19]:
# Reset the index to get consecutive index numbers
pugetsound_tides_currents.reset_index(drop=True, inplace=True)

In [20]:
pugetsound_tides_currents.head(50)

,Dive_Site,Date,Day_of_Week,Time,Event,Current_Speed_(knots),Height (cm),Height (ft),Current_Station_Name,Current_Station_ID,Tide_Station_Name,Tide_Station_ID,Latitude,Longitude
0,Alki,2024-01-01,Monday,00:24:00,ebb,-0.5,NaN,NaN,HARBOR ISLAND WEST,PUG1507,NaN,NaN,47.588707,-122.380009
1,Alki,2024-01-01,Monday,01:34:00,Low,NaN,20.0,0.66,NaN,NaN,LOCKHEED SHIPYARD,9447110,47.588707,-122.380009
2,Alki,2024-01-01,Monday,04:00:00,slack,0.0,NaN,NaN,HARBOR ISLAND WEST,PUG1508,NaN,NaN,47.588707,-122.380009
3,Alki,2024-01-01,Monday,06:12:00,flood,0.1,NaN,NaN,HARBOR ISLAND WEST,PUG1509,NaN,NaN,47.588707,-122.380009
4,Alki,2024-01-01,Monday,08:36:00,slack,0.0,NaN,NaN,HARBOR ISLAND WEST,PUG1510,NaN,NaN,47.588707,-122.380009
5,Alki,2024-01-01,Monday,08:56:00,High,NaN,364.0,11.95,NaN,NaN,LOCKHEED SHIPYARD,9447110,47.588707,-122.380009
6,Alki,2024-01-01,Monday,12:12:00,ebb,-0.2,NaN,NaN,HARBOR ISLAND WEST,PUG1511,NaN,NaN,47.588707,-122.380009
7,Alki,2024-01-01,Monday,14:24:00,slack,0.0,NaN,NaN,HARBOR ISLAND WEST,PUG1512,NaN,NaN,47.588707,-122.380009
8,Alki,2024-01-01,Monday,15:22:00,Low,NaN,181.0,5.95,NaN,NaN,LOCKHEED SHIPYARD,9447110,47.588707,-122.380009
9,Alki,2024-01-01,Monday,17:24:00,slack,0.0,NaN,NaN,HARBOR ISLAND WEST,PUG1513,NaN,NaN,47.588707,-122.380009
10,Alki,2024-01-01,Monday,19:57:00,High,NaN,245.0,8.05,NaN,NaN,LOCKHEED SHIPYARD,9447110,47.588707,-122.380009
11,Alki,2024-01-02,Tuesday,01:18:00,ebb,-0.4,NaN,NaN,HARBOR ISLAND WEST,PUG1514,NaN,NaN,47.588707,-122.380009
12,Alki,2024-01-02,Tuesday,02:12:00,Low,NaN,58.0,1.89,NaN,NaN,LOCKHEED SHIPYARD,9447110,47.588707,-122.380009
13,Alki,2024-01-02,Tuesday,04:42:00,slack,0.0,NaN,NaN,HARBOR ISLAND WEST,PUG1515,NaN,NaN,47.588707,-122.380009
14,Alki,2024-01-02,Tuesday,07:06:00,flood,0.1,NaN,NaN,HARBOR ISLAND WEST,PUG1516,NaN,NaN,47.588707,-122.380009
15,Alki,2024-01-02,Tuesday,09:24:00,slack,0.0,NaN,NaN,HARBOR ISLAND WEST,PUG1517,NaN,NaN,47.588707,-122.380009
16,Alki,2024-01-02,Tuesday,09:27:00,High,NaN,361.0,11.84,NaN,NaN,LOCKHEED SHIPYARD,9447110,47.588707,-122.380009
17,Alki,2024-01-02,Tuesday,13:12:00,ebb,-0.2,NaN,NaN,HARBOR ISLAND WEST,PUG1518,NaN,NaN,47.588707,-122.380009
18,Alki,2024-01-02,Tuesday,16:11:00,Low,NaN,155.0,5.09,NaN,NaN,LOCKHEED SHIPYARD,9447110,47.588707,-122.380009
19,Alki,2024-01-02,Tuesday,16:42:00,slack,0.0,NaN,NaN,HARBOR ISLAND WEST,PUG1519,NaN,NaN,47.588707,-122.380009
20,Alki,2024-01-02,Tuesday,19:00:00,slack,0.0,NaN,NaN,HARBOR ISLAND WEST,PUG1520,NaN,NaN,47.588707,-122.380009
21,Alki,2024-01-02,Tuesday,20:24:00,slack,0.0,NaN,NaN,HARBOR ISLAND WEST,PUG1521,NaN,NaN,47.588707,-122.380009
22,Alki,2024-01-02,Tuesday,21:07:00,High,NaN,230.0,7.54,NaN,NaN,LOCKHEED SHIPYARD,9447110,47.588707,-122.380009
23,Alki,2024-01-03,Wednesday,02:12:00,ebb,-0.3,NaN,NaN,HARBOR ISLAND WEST,PUG1522,NaN,NaN,47.588707,-122.380009
24,Alki,2024-01-03,Wednesday,02:52:00,Low,NaN,102.0,3.34,NaN,NaN,LOCKHEED SHIPYARD,9447110,47.588707,-122.380009
25,Alki,2024-01-03,Wednesday,05:12:00,slack,0.0,NaN,NaN,HARBOR ISLAND WEST,PUG1523,NaN,NaN,47.588707,-122.380009
26,Alki,2024-01-03,Wednesday,08:12:00,flood,0.1,NaN,NaN,HARBOR ISLAND WEST,PUG1524,NaN,NaN,47.588707,-122.380009
27,Alki,2024-01-03,Wednesday,09:59:00,High,NaN,356.0,11.68,NaN,NaN,LOCKHEED SHIPYARD,9447110,47.588707,-122.380009
28,Alki,2024-01-03,Wednesday,10:12:00,slack,0.0,NaN,NaN,HARBOR ISLAND WEST,PUG1525,NaN,NaN,47.588707,-122.380009
29,Alki,2024-01-03,Wednesday,14:30:00,ebb,-0.3,NaN,NaN,HARBOR ISLAND WEST,PUG1526,NaN,NaN,47.588707,-122.380009
30,Alki,2024-01-03,Wednesday,17:00:00,Low,NaN,125.0,4.09,NaN,NaN,LOCKHEED SHIPYARD,9447110,47.588707,-122.380009
31,Alki,2024-01-03,Wednesday,20:54:00,slack,0.0,NaN,NaN,HARBOR ISLAND WEST,PUG1527,NaN,NaN,47.588707,-122.380009
32,Alki,2024-01-03,Wednesday,22:06:00,slack,0.0,NaN,NaN,HARBOR ISLAND WEST,PUG1528,NaN,NaN,47.588707,-122.380009
33,Alki,2024-01-03,Wednesday,22:32:00,High,NaN,223.0,7.33,NaN,NaN,LOCKHEED SHIPYARD,9447110,47.588707,-122.380009
34,Alki,2024-01-04,Thursday,03:00:00,ebb,-0.2,NaN,NaN,HARBOR ISLAND WEST,PUG1529,NaN,NaN,47.588707,-122.380009
35,Alki,2024-01-04,Thursday,03:35:00,Low,NaN,150.0,4.93,NaN,NaN,LOCKHEED SHIPYARD,9447110,47.588707,-122.380009
36,Alki,2024-01-04,Thursday,05:24:00,slack,0.0,NaN,NaN,HARBOR ISLAND WEST,PUG1530,NaN,NaN,47.588707,-122.380009
37,Alki,2024-01-04,Thursday,08:54:00,flood,0.1,NaN,NaN,HARBOR ISLAND WEST,PUG1531,NaN,NaN,47.588707,-122.380009
38,Alki,2024-01-04,Thursday,10:31:00,High,NaN,350.0,11.48,NaN,NaN,LOCKHEED SHIPYARD,9447110,47.588707,-122.380009
39,Alki,2024-01-04,Thursday,10:48:00,slack,0.0,NaN,NaN,HARBOR ISLAND WEST,PUG1532,NaN,NaN,47.588707,-122.380009
40,Alki,2024-01-04,Thursday,15:30:00,ebb,-0.4,NaN,NaN,HARBOR ISLAND WEST,PUG1533,NaN,NaN,47.588707,-122.380009
41,Alki,2024-01-04,Thursday,17:46:00,Low,NaN,91.0,2.99,NaN,NaN,LOCKHEED SHIPYARD,9447110,47.588707,-122.380009
42,Alki,2024-01-04,Thursday,20:48:00,slack,0.0,NaN,NaN,HARBOR ISLAND WEST,PUG1534,NaN,NaN,47.588707,-122.380009
43,Alki,2024-01-05,Friday,00:15:00,High,NaN,234.0,7.67,NaN,NaN,LOCKHEED SHIPYARD,9447110,47.588707,-122.380009
44,Alki,2024-01-05,Friday,00:24:00,slack,0.0,NaN,NaN,HARBOR ISLAND WEST,PUG1535,NaN,NaN,47.588707,-122.380009
45,Alki,2024-01-05,Friday,03:54:00,ebb,-0.1,NaN,NaN,HARBOR ISLAND WEST,PUG1536,NaN,NaN,47.588707,-122.380009
46,Alki,2024-01-05,Friday,04:30:00,Low,NaN,198.0,6.51,NaN,NaN,LOCKHEED SHIPYARD,9447110,47.588707,-122.380009
47,Alki,2024-01-05,Friday,05:48:00,slack,0.0,NaN,NaN,HARBOR ISLAND WEST,PUG1537,NaN,NaN,47.588707,-122.380009
48,Alki,2024-01-05,Friday,09:24:00,flood,0.1,NaN,NaN,HARBOR ISLAND WEST,PUG1538,NaN,NaN,47.588707,-122.380009
49,Alki,2024-01-05,Friday,11:05:00,High,NaN,343.0,11.25,NaN,NaN,LOCKHEED SHIPYARD,9447110,47.588707,-122.380009

In [21]:
# Export pugetsound_tides_currents dataset as pickle
#pugetsound_tides_currents.to_pickle(os.path.join(path, '02 Data','Prepared Data', 'pugetsound_tides_currents.pkl'))

In [22]:
# Export pugetsound_tides_currents dataset as csv
#pugetsound_tides_currents.to_csv(os.path.join(path, '02 Data','Prepared Data', 'pugetsound_tides_currents.csv'))